# numpy

In [4]:
#Numpy is numerical python

In [5]:

import numpy as np

# Numpy function

In [6]:

A1 = np.array([[11,12,13],[14,15,16]])

In [7]:
A1

array([[11, 12, 13],
       [14, 15, 16]])

In [8]:
A2 = np.zeros((15,16), dtype = int)

In [9]:
A2

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [10]:

A3 = np.arange(2,10,2)

In [11]:
A3

array([2, 4, 6, 8])

In [12]:

A4 = np.ones((13,14) , dtype = int)

In [13]:
A4

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [15]:
A5 = np.linspace(10,30,3)

In [16]:
A5

array([10., 20., 30.])

In [17]:
A6 = np.random.randint(0,15,size=(13,14))

In [18]:
A6

array([[ 0, 14,  8, 10,  2,  6, 10,  2, 11, 14,  3,  0, 10,  3],
       [11,  1, 10,  4,  7,  8, 12,  3, 12,  3,  8,  3, 13,  6],
       [ 3,  1,  2, 12,  8, 14, 13, 14, 14, 11,  6,  7, 14, 11],
       [ 2, 13,  6,  6, 12, 14,  6,  2, 14,  4, 14,  2,  4, 14],
       [ 6,  0, 10,  0,  7,  8,  9, 13,  3, 10,  7,  2,  4,  4],
       [ 9,  7,  7, 14, 12,  1,  2,  2, 14,  5, 14,  3,  1,  6],
       [ 5,  9,  0, 12,  8,  8,  4,  4,  3,  0, 14,  5,  4,  6],
       [14,  0,  8, 13,  4,  3, 11, 14,  4,  5,  2,  7,  6,  4],
       [ 5, 11,  7, 12, 14,  6,  2,  1, 12,  0,  3,  5, 11,  6],
       [ 3, 11, 11, 12, 13, 12,  6,  7,  7, 12,  0, 10,  9,  2],
       [ 4,  3,  3, 14,  7, 13,  5, 10,  2,  2,  8,  0, 12, 14],
       [14,  5,  6,  0,  2,  6, 12, 14,  9,  8,  9,  3,  5,  0],
       [ 1,  9, 11, 11, 12, 13,  4,  5,  2, 13,  1, 10,  5, 10]])

In [19]:
A7 = np.full((2,2,2),14)

In [20]:
A7

array([[[14, 14],
        [14, 14]],

       [[14, 14],
        [14, 14]]])

In [22]:
A8 = np.identity(14)

In [23]:
A8

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [24]:
list = [11,12,13,14,15]
A9 = np.asarray(list)

In [25]:
A9

array([11, 12, 13, 14, 15])

In [28]:
a = (15,10)
b = (15,12)

In [29]:
np.divide(a,b)

array([1.        , 0.83333333])

In [30]:

divide =np.divide(10,5)

In [31]:
divide

2.0

In [32]:
mul =np.multiply(10,5)

In [33]:
mul

50

# aggregation operation

In [34]:
data = np.random.randint(1,10,(2,4))

In [35]:
data

array([[1, 3, 3, 1],
       [6, 1, 1, 2]])

In [36]:
#sum
print(np.sum(data))
print(np.sum(data,axis=0))
print(np.sum(data,axis=1))

18
[7 4 4 3]
[ 8 10]


In [37]:
data.max()

6

In [38]:

data.min()

1

# numpy array attributes

In [39]:
a1 =np.array([[11,12,13],[14,15,16]])
print(a1.shape)

(2, 3)


In [40]:
a2 = np.array([[1,2,3],[4,5,6]])
print(f"the dimension of a2:",a2.ndim)

the dimension of a2: 2


In [41]:
a3 = np.array([[11,12,13],[14,15,16]])
print(f"elments in a3 = {a3.size}")

elments in a3 = 6


In [42]:
a5 = np.array([1,2,3])
print(a5.dtype)

int32


# array maniupulation

In [43]:
a6 = np.array(np.random.randint(1,6,(6,3)))
a6

array([[3, 1, 2],
       [5, 2, 3],
       [1, 4, 4],
       [3, 4, 3],
       [5, 2, 2],
       [5, 2, 2]])

In [44]:
transpose_array = np.transpose(a6)

In [45]:
transpose_array 

array([[3, 5, 1, 3, 5, 5],
       [1, 2, 4, 4, 2, 2],
       [2, 3, 4, 3, 2, 2]])

In [46]:

a7 = np.array(np.random.randint(1,6,(6,3)))

In [47]:
a7

array([[5, 3, 1],
       [5, 3, 1],
       [4, 1, 4],
       [4, 1, 2],
       [3, 1, 3],
       [1, 1, 4]])

In [48]:
a7 = np.array(np.random.randint(1,6,(6,2)))
a7

array([[2, 4],
       [2, 5],
       [5, 1],
       [2, 5],
       [5, 5],
       [5, 1]])

In [49]:

a7.flatten()

array([2, 4, 2, 5, 5, 1, 2, 5, 5, 5, 5, 1])